// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: calculator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalculatorService_Sum_FullMethodName           = "/calculator.CalculatorService/Sum"
	CalculatorService_SumMany_FullMethodName       = "/calculator.CalculatorService/SumMany"
	CalculatorService_CountDown_FullMethodName     = "/calculator.CalculatorService/CountDown"
	CalculatorService_CumulativeSum_FullMethodName = "/calculator.CalculatorService/CumulativeSum"
	CalculatorService_SquareRoot_FullMethodName    = "/calculator.CalculatorService/SquareRoot"
	CalculatorService_SumDelay_FullMethodName      = "/calculator.CalculatorService/SumDelay"
)

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	SumMany(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SumManyRequest, SumManyResponse], error)
	CountDown(ctx context.Context, in *CountDownRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CountDownResponse], error)
	CumulativeSum(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CumulativeSumRequest, CumulativeSumResponse], error)
	SquareRoot(ctx context.Context, in *SqrRootRequest, opts ...grpc.CallOption) (*SqrRootResponse, error)
	SumDelay(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, CalculatorService_Sum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) SumMany(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SumManyRequest, SumManyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[0], CalculatorService_SumMany_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SumManyRequest, SumManyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculatorService_SumManyClient = grpc.ClientStreamingClient[SumManyRequest, SumManyResponse]

func (c *calculatorServiceClient) CountDown(ctx context.Context, in *CountDownRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CountDownResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[1], CalculatorService_CountDown_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CountDownRequest, CountDownResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculatorService_CountDownClient = grpc.ServerStreamingClient[CountDownResponse]

func (c *calculatorServiceClient) CumulativeSum(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CumulativeSumRequest, CumulativeSumResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CalculatorService_ServiceDesc.Streams[2], CalculatorService_CumulativeSum_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CumulativeSumRequest, CumulativeSumResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculatorService_CumulativeSumClient = grpc.BidiStreamingClient[CumulativeSumRequest, CumulativeSumResponse]

func (c *calculatorServiceClient) SquareRoot(ctx context.Context, in *SqrRootRequest, opts ...grpc.CallOption) (*SqrRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqrRootResponse)
	err := c.cc.Invoke(ctx, CalculatorService_SquareRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) SumDelay(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, CalculatorService_SumDelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
// All implementations must embed UnimplementedCalculatorServiceServer
// for forward compatibility.
type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	SumMany(grpc.ClientStreamingServer[SumManyRequest, SumManyResponse]) error
	CountDown(*CountDownRequest, grpc.ServerStreamingServer[CountDownResponse]) error
	CumulativeSum(grpc.BidiStreamingServer[CumulativeSumRequest, CumulativeSumResponse]) error
	SquareRoot(context.Context, *SqrRootRequest) (*SqrRootResponse, error)
	SumDelay(context.Context, *SumRequest) (*SumResponse, error)
	mustEmbedUnimplementedCalculatorServiceServer()
}

// UnimplementedCalculatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalculatorServiceServer struct{}

func (UnimplementedCalculatorServiceServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedCalculatorServiceServer) SumMany(grpc.ClientStreamingServer[SumManyRequest, SumManyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SumMany not implemented")
}
func (UnimplementedCalculatorServiceServer) CountDown(*CountDownRequest, grpc.ServerStreamingServer[CountDownResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CountDown not implemented")
}
func (UnimplementedCalculatorServiceServer) CumulativeSum(grpc.BidiStreamingServer[CumulativeSumRequest, CumulativeSumResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CumulativeSum not implemented")
}
func (UnimplementedCalculatorServiceServer) SquareRoot(context.Context, *SqrRootRequest) (*SqrRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SquareRoot not implemented")
}
func (UnimplementedCalculatorServiceServer) SumDelay(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SumDelay not implemented")
}
func (UnimplementedCalculatorServiceServer) mustEmbedUnimplementedCalculatorServiceServer() {}
func (UnimplementedCalculatorServiceServer) testEmbeddedByValue()                           {}

// UnsafeCalculatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServiceServer will
// result in compilation errors.
type UnsafeCalculatorServiceServer interface {
	mustEmbedUnimplementedCalculatorServiceServer()
}

func RegisterCalculatorServiceServer(s grpc.ServiceRegistrar, srv CalculatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCalculatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalculatorService_ServiceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalculatorService_Sum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_SumMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).SumMany(&grpc.GenericServerStream[SumManyRequest, SumManyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculatorService_SumManyServer = grpc.ClientStreamingServer[SumManyRequest, SumManyResponse]

func _CalculatorService_CountDown_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CountDownRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).CountDown(m, &grpc.GenericServerStream[CountDownRequest, CountDownResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculatorService_CountDownServer = grpc.ServerStreamingServer[CountDownResponse]

func _CalculatorService_CumulativeSum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).CumulativeSum(&grpc.GenericServerStream[CumulativeSumRequest, CumulativeSumResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CalculatorService_CumulativeSumServer = grpc.BidiStreamingServer[CumulativeSumRequest, CumulativeSumResponse]

func _CalculatorService_SquareRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqrRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).SquareRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalculatorService_SquareRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).SquareRoot(ctx, req.(*SqrRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_SumDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).SumDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalculatorService_SumDelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).SumDelay(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalculatorService_ServiceDesc is the grpc.ServiceDesc for CalculatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
		{
			MethodName: "SquareRoot",
			Handler:    _CalculatorService_SquareRoot_Handler,
		},
		{
			MethodName: "SumDelay",
			Handler:    _CalculatorService_SumDelay_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SumMany",
			Handler:       _CalculatorService_SumMany_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CountDown",
			Handler:       _CalculatorService_CountDown_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CumulativeSum",
			Handler:       _CalculatorService_CumulativeSum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator.proto",
}
